//! Towns that every world grows by itself, whatever datadisks it uses.
//!
//! A world has a few dozen settlements (`ISHTARIA_SETTLEMENTS`, default 36; 0 for none), each
//! with a graveyard outside its edge. They are ordinary places of a built-in disk named `world`,
//! so they are placed, persisted and described like any other place. After placement, settlements
//! by the sea get a harbour with a shipwright (a second built-in disk, `harbours`) who sells boats
//! and ships for gold.

use super::{
    disk::{Dialogue, Disk, HeightRange, Manifest, Music, Near, Npc, Place, Requires, Scenery},
    placement::{self, Ground, Placed},
    Story,
};
use crate::movement::WorldObject;
use crate::scenery::{self, LocalProp, Size};
use anyhow::Result;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;

const DEFAULT_COUNT: usize = 36;
const SPACING_M: f64 = 120_000.0;
const SHIPWRIGHT: &str = include_str!("../../etc/shipwright.yaml");
const GATE_GUARD: &str = include_str!("../../etc/gate_guard.yaml");
/// Directory with the files the server itself ships (override with `ISHTARIA_ASSETS_DIR`).
const DEFAULT_ASSETS_DIR: &str = "/usr/share/ishtaria-server";
/// Default music of every generated graveyard, below the assets directory.
const GRAVEYARD_MUSIC: &str = "music/graveyard_midnightcem.ogg";
/// How far from a graveyard its music is heard.
const GRAVEYARD_MUSIC_RADIUS_M: f64 = 70.0;

fn assets_dir() -> PathBuf {
    std::env::var_os("ISHTARIA_ASSETS_DIR").map_or_else(
        || {
            if cfg!(test) {
                PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/assets"))
            } else {
                PathBuf::from(DEFAULT_ASSETS_DIR)
            }
        },
        PathBuf::from,
    )
}

/// How many settlements a world grows.
pub fn count() -> usize {
    // Tests build tiny worlds with no room for towns unless they ask for some.
    let default = if cfg!(test) { 0 } else { DEFAULT_COUNT };
    std::env::var("ISHTARIA_SETTLEMENTS")
        .ok()
        .and_then(|value| value.parse::<usize>().ok())
        .map_or(default, |value| value.min(200))
}

/// A model standing in the world, as sent to clients.
#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct WorldProp {
    pub id: String,
    /// `<kit>.<name>` of a bundled Kenney kit model.
    pub model: String,
    pub position: [f64; 3],
    pub yaw: f64,
    /// Metres per model unit.
    pub scale_m: f64,
}

fn manifest(id: &str, name: &str) -> Manifest {
    Manifest {
        id: id.to_owned(),
        version: "1.0.0".to_owned(),
        name: name.to_owned(),
        description: String::new(),
        requires_ruleset: "1".to_owned(),
        license: "AGPL-3.0-only".to_owned(),
        attribution: "Generated by ishtaria-server".to_owned(),
        rating: None,
        cover: None,
        languages: vec!["en".to_owned(), "cs".to_owned()],
        requires: Vec::new(),
        conflicts: Vec::new(),
    }
}

fn empty_disk(manifest: Manifest) -> Disk {
    Disk {
        manifest,
        sha256: String::new(),
        places: Vec::new(),
        npcs: Vec::new(),
        dialogues: Vec::new(),
        quests: Vec::new(),
        lore: Vec::new(),
        music: Vec::new(),
        media: BTreeMap::new(),
        voices: BTreeMap::new(),
        strings: BTreeMap::from([
            ("en".to_owned(), BTreeMap::new()),
            ("cs".to_owned(), BTreeMap::new()),
        ]),
    }
}

/// A pronounceable place name from a hash of the world seed.
fn town_name(seed: &str, index: usize) -> String {
    const START: [&str; 14] = [
        "Bel", "Dor", "Ash", "Kar", "Mor", "Thal", "Vel", "Rin", "Sar", "Olm", "Eld", "Hav", "Wyn",
        "Tor",
    ];
    const MIDDLE: [&str; 8] = ["a", "en", "o", "i", "ur", "an", "e", "ow"];
    const END: [&str; 12] = [
        "ford", "wick", "haven", "ton", "mere", "stead", "bury", "dale", "port", "ham", "by",
        "gate",
    ];
    let hash = Sha256::digest(format!("ishtaria-town-name:{seed}:{index}").as_bytes());
    let pick = |offset: usize, len: usize| hash[offset] as usize % len;
    format!(
        "{}{}{}",
        START[pick(0, START.len())],
        MIDDLE[pick(1, MIDDLE.len())],
        END[pick(2, END.len())]
    )
}

fn size_of(seed: &str, index: usize) -> Size {
    let hash = Sha256::digest(format!("ishtaria-town-size:{seed}:{index}").as_bytes());
    match hash[0] % 20 {
        0..=8 => Size::Hamlet,
        9..=16 => Size::Village,
        _ => Size::Town,
    }
}

fn size_name(size: Size) -> &'static str {
    match size {
        Size::Hamlet => "hamlet",
        Size::Village => "village",
        Size::Town => "town",
    }
}

/// Adds the default graveyard track to the disk and returns its id, if the file is installed.
fn graveyard_music(disk: &mut Disk) -> Option<String> {
    let path = assets_dir().join(GRAVEYARD_MUSIC);
    let bytes = std::fs::read(&path).ok()?;
    let relative = "media/music/graveyard.ogg";
    disk.music.push(Music {
        id: "graveyard".to_owned(),
        file: relative.to_owned(),
        title_key: "music.graveyard".to_owned(),
        looped: true,
    });
    disk.media.insert(
        relative.to_owned(),
        (path, format!("{:x}", Sha256::digest(&bytes))),
    );
    for language in ["en", "cs"] {
        disk.strings.get_mut(language).unwrap().insert(
            "music.graveyard".to_owned(),
            "Midnightcem (Tozan, CC0)".to_owned(),
        );
    }
    Some("graveyard".to_owned())
}

/// The built-in disk `world`: `count` settlements and their graveyards.
pub fn world_disk(seed: &str, count: usize) -> Disk {
    let mut disk = empty_disk(manifest("world", "Settlements"));
    // Without the file (a server installed without its assets) the graveyards are silent
    // rather than the world broken.
    let graveyard_music = graveyard_music(&mut disk);
    for index in 0..count {
        let size = size_of(seed, index);
        let name = town_name(seed, index);
        let town = format!("town_{index:02}");
        let graveyard = format!("{town}_graveyard");
        disk.places.push(Place {
            id: town.clone(),
            kind: "city".to_owned(),
            name_key: format!("{town}.name"),
            parent: None,
            radius_m: Some(size.radius_m() + 20.0),
            spacing_m: Some(SPACING_M),
            spawn: false,
            at: None,
            music: None,
            music_radius_m: None,
            scenery: Some(Scenery {
                preset: "town".to_owned(),
                size: Some(size_name(size).to_owned()),
            }),
            requires: Requires {
                biome: vec![
                    "lowland".into(),
                    "grassland".into(),
                    "temperate_forest".into(),
                ],
                height_m: Some(HeightRange {
                    min: Some(3.0),
                    max: Some(700.0),
                }),
                max_slope_deg: Some(10.0),
                // One in four is founded by the sea, so that every world has harbours.
                coast: (index % 4 == 0).then_some(true),
                near: Vec::new(),
            },
        });
        disk.places.push(Place {
            id: graveyard.clone(),
            kind: "graveyard".to_owned(),
            name_key: format!("{graveyard}.name"),
            parent: None,
            radius_m: Some(24.0),
            spacing_m: None,
            spawn: false,
            at: None,
            music: graveyard_music.clone(),
            music_radius_m: graveyard_music.as_ref().map(|_| GRAVEYARD_MUSIC_RADIUS_M),
            scenery: Some(Scenery {
                preset: "graveyard".to_owned(),
                size: None,
            }),
            requires: Requires {
                max_slope_deg: Some(15.0),
                near: vec![Near {
                    place: town,
                    min_m: 140.0,
                    max_m: 230.0,
                }],
                ..Requires::default()
            },
        });
        disk.strings
            .get_mut("en")
            .unwrap()
            .insert(format!("town_{index:02}.name"), name.clone());
        disk.strings
            .get_mut("cs")
            .unwrap()
            .insert(format!("town_{index:02}.name"), name.clone());
        disk.strings
            .get_mut("en")
            .unwrap()
            .insert(format!("{graveyard}.name"), format!("{name} Graveyard"));
        disk.strings
            .get_mut("cs")
            .unwrap()
            .insert(format!("{graveyard}.name"), format!("Hřbitov {name}"));
    }
    // A fortress guards every fourth town. They come after all towns and graveyards, so the
    // places that were there before keep their order, and the disk's hash below does not change:
    // a world generated earlier simply places its new fortresses the next time it is loaded.
    for index in 0..count / 4 {
        let town = format!("town_{:02}", index * 4 + 1);
        let fort = format!("fort_{index:02}");
        let name = town_name(seed, 1000 + index);
        disk.places.push(Place {
            id: fort.clone(),
            kind: "landmark".to_owned(),
            name_key: format!("{fort}.name"),
            parent: None,
            radius_m: Some(scenery::FORTRESS_RADIUS_M + 14.0),
            spacing_m: None,
            spawn: false,
            at: None,
            music: None,
            music_radius_m: None,
            scenery: Some(Scenery {
                preset: "fortress".to_owned(),
                size: None,
            }),
            requires: Requires {
                biome: vec![
                    "lowland".into(),
                    "grassland".into(),
                    "temperate_forest".into(),
                    "mountain".into(),
                ],
                height_m: Some(HeightRange {
                    min: Some(3.0),
                    max: Some(900.0),
                }),
                max_slope_deg: Some(8.0),
                near: vec![Near {
                    place: town,
                    min_m: 300.0,
                    max_m: 1200.0,
                }],
                ..Requires::default()
            },
        });
        disk.strings
            .get_mut("en")
            .unwrap()
            .insert(format!("{fort}.name"), format!("{name} Fortress"));
        disk.strings
            .get_mut("cs")
            .unwrap()
            .insert(format!("{fort}.name"), format!("Pevnost {name}"));
    }
    // Every walled town has a guard at its gate. Like the fortresses, they come last, so that the
    // places that were there before keep their order.
    let mut guarded = false;
    for index in 0..count {
        if size_of(seed, index) != Size::Town {
            continue;
        }
        guarded = true;
        let gate = format!("town_{index:02}_gate");
        disk.places.push(Place {
            id: gate.clone(),
            kind: "landmark".to_owned(),
            name_key: "gate.name".to_owned(),
            parent: Some(format!("town_{index:02}")),
            radius_m: Some(10.0),
            spacing_m: None,
            spawn: false,
            at: Some("gate".to_owned()),
            music: None,
            music_radius_m: None,
            scenery: None,
            requires: Requires::default(),
        });
        disk.npcs.push(Npc {
            id: format!("guard_{index:02}"),
            name_key: "gate_guard.name".to_owned(),
            place: gate,
            character: super::disk::Character {
                pack: "retro".to_owned(),
                skin: "humanMaleA".to_owned(),
                model: None,
            },
            dialogue: "gate_guard".to_owned(),
            bio_key: Some("gate_guard.bio".to_owned()),
            portrait: None,
            tags: vec!["guard".to_owned()],
        });
    }
    if guarded {
        let file: DialogueFile =
            serde_yaml::from_str(GATE_GUARD).expect("the built-in gate guard is valid");
        disk.dialogues.push(file.dialogue);
        for (language, table) in file.strings {
            disk.strings.entry(language).or_default().extend(table);
        }
    }
    disk.sha256 = format!(
        "{:x}",
        Sha256::digest(format!("world:{seed}:{count}").as_bytes())
    );
    disk
}

#[derive(Deserialize)]
struct DialogueFile {
    dialogue: Dialogue,
    strings: BTreeMap<String, BTreeMap<String, String>>,
}

/// What a built place leaves in the world: models to draw and obstacles to walk around.
#[derive(Default)]
pub struct Built {
    pub props: Vec<WorldProp>,
    pub colliders: Vec<WorldObject>,
    /// Settlements with a pasture where farm animals graze.
    pub farms: Vec<crate::movement::FarmSite>,
}

fn to_props(
    id: &str,
    site: &Placed,
    local: Vec<LocalProp>,
    ground: &dyn Ground,
    built: &mut Built,
) {
    let props = &mut built.props;
    for (number, prop) in local.into_iter().enumerate() {
        if !prop.at_sea {
            for (k, circle) in scenery::colliders(&prop).into_iter().enumerate() {
                let (_, position) = scenery::world_from_local(
                    site.direction,
                    circle.x,
                    circle.z,
                    |direction| ground.height(direction).max(0.0),
                    crate::movement::RADIUS,
                );
                built.colliders.push(WorldObject {
                    id: format!("{id}#{number}.{k}"),
                    model: String::new(),
                    position,
                    scale_m: 1.0,
                    yaw: 0.0,
                    collision_radius_m: circle.radius,
                    biome: 4,
                });
            }
        }
        let (_, position) = scenery::world_from_local(
            site.direction,
            prop.x,
            prop.z,
            |direction| {
                if prop.at_sea {
                    prop.y
                } else {
                    ground.height(direction).max(0.0) + prop.y
                }
            },
            crate::movement::RADIUS,
        );
        props.push(WorldProp {
            id: format!("{id}#{number}"),
            model: prop.model,
            position,
            yaw: prop.yaw,
            scale_m: prop.scale,
        });
    }
}

/// Builds what depends on where the places ended up: the scenery of every place that has one,
/// and a harbour with a shipwright for each settlement by the sea. Harbour sites are derived
/// from the settlement's site, so they are not stored.
pub fn finish(
    story: &mut Story,
    sites: &mut HashMap<String, Placed>,
    ground: &dyn Ground,
    seed: &str,
) -> Result<Built> {
    let mut built = Built::default();
    let mut harbours: Vec<(usize, Placed)> = Vec::new();
    let anchors = story.anchors.clone();
    for (index, anchor) in anchors.iter().enumerate() {
        let (Some(scenery), Some(site)) = (&anchor.place.scenery, sites.get(&anchor.id)) else {
            continue;
        };
        let site = site.clone();
        match scenery.preset.as_str() {
            "town" => {
                let size = scenery
                    .size
                    .as_deref()
                    .and_then(Size::parse)
                    .unwrap_or(Size::Village);
                let sea = placement::sea_toward(ground, site.direction, placement::COAST_M);
                built.farms.push(crate::movement::FarmSite {
                    id: anchor.id.clone(),
                    direction: site.direction,
                    radius_m: size.radius_m(),
                });
                to_props(
                    &anchor.id,
                    &site,
                    scenery::settlement(seed, &anchor.id, size, sea),
                    ground,
                    &mut built,
                );
                if let Some(((hx, hz), distance)) = sea {
                    // The landing: a little before the water, along the heading to the sea.
                    let reach = (distance - 6.0).max(4.0);
                    let (direction, _) = scenery::world_from_local(
                        site.direction,
                        hx * reach,
                        hz * reach,
                        |_| 0.0,
                        crate::movement::RADIUS,
                    );
                    harbours.push((
                        index,
                        Placed {
                            id: format!("harbours:harbour_{index:02}"),
                            direction,
                            height_m: ground.height(direction).max(0.0),
                        },
                    ));
                }
            }
            "fortress" => {
                to_props(
                    &anchor.id,
                    &site,
                    scenery::fortress(seed, &anchor.id),
                    ground,
                    &mut built,
                );
            }
            "graveyard" => {
                let radius = anchor.place.radius_m.unwrap_or(24.0) * 0.65;
                to_props(
                    &anchor.id,
                    &site,
                    scenery::graveyard(seed, &anchor.id, radius),
                    ground,
                    &mut built,
                );
            }
            _ => {}
        }
    }
    if !harbours.is_empty() {
        let file: DialogueFile = serde_yaml::from_str(SHIPWRIGHT)?;
        let mut disk = empty_disk(manifest("harbours", "Harbours"));
        disk.dialogues.push(file.dialogue);
        for (language, table) in file.strings {
            disk.strings.entry(language).or_default().extend(table);
        }
        for (index, site) in &harbours {
            let local = format!("harbour_{index:02}");
            disk.places.push(Place {
                id: local.clone(),
                kind: "landmark".to_owned(),
                name_key: "harbour.name".to_owned(),
                parent: None,
                radius_m: Some(14.0),
                spacing_m: None,
                spawn: false,
                at: None,
                music: None,
                music_radius_m: None,
                scenery: None,
                requires: Requires::default(),
            });
            disk.npcs.push(Npc {
                id: format!("shipwright_{index:02}"),
                name_key: "shipwright.name".to_owned(),
                place: local,
                character: super::disk::Character {
                    pack: "retro".to_owned(),
                    skin: "humanMaleA".to_owned(),
                    model: None,
                },
                dialogue: "shipwright".to_owned(),
                bio_key: Some("shipwright.bio".to_owned()),
                portrait: None,
                tags: vec!["shop".to_owned()],
            });
            sites.insert(site.id.clone(), site.clone());
        }
        disk.sha256 = format!(
            "{:x}",
            Sha256::digest(format!("harbours:{}", harbours.len()).as_bytes())
        );
        story.add_disk(disk)?;
        story.check()?;
    }
    Ok(built)
}
