ALTER TABLE players
    ADD COLUMN movement_airborne BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN movement_support BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN jump_vertical_speed DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (jump_vertical_speed BETWEEN -100 AND 10),
    ADD COLUMN jump_x DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (jump_x BETWEEN -4.01 AND 4.01),
    ADD COLUMN jump_y DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (jump_y BETWEEN -4.01 AND 4.01),
    ADD COLUMN jump_z DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (jump_z BETWEEN -4.01 AND 4.01);